name: python app for NLP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: |
          make install

      - name: Run pylint
        run: |
          make lint

      - name: Test code
        run: |
          make test

      - name: Format code
        run: |
          make format
